# Generated by Django 2.0.4 on 2018-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_info',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=32)),
                ('creat_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=16)),
                ('seniority', models.CharField(max_length=32)),
                ('r_id', models.ForeignKey(on_delete='did', to='app1.department_info')),
            ],
        ),
    ]
