# Generated by Django 2.0.4 on 2018-04-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_department_info_doctor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_info',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
