# Generated by Django 2.0.4 on 2018-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180430_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department_info',
            name='creat_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
