# Generated by Django 2.0.4 on 2018-05-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180430_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ap_success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_time', models.DateField(auto_now_add=True)),
                ('num', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete='id', to='app1.doctor_info')),
            ],
        ),
    ]
