# Generated by Django 2.0.4 on 2018-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_ap_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ap_success',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='doctor_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
